"""change id to uuid string

Revision ID: 011bf31fdac5
Revises: a0b0ffb7d8f1
Create Date: 2024-06-17 17:22:34.881919

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '011bf31fdac5'
down_revision = 'a0b0ffb7d8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allegro_tokens', 'id_',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index('ix_allegro_tokens_id_', table_name='allegro_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_allegro_tokens_id_', 'allegro_tokens', ['id_'], unique=False)
    op.alter_column('allegro_tokens', 'id_',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
