"""add 'belongs_to' col

Revision ID: a0b0ffb7d8f1
Revises: b8c7ebc6d275
Create Date: 2024-06-17 15:49:20.427331

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a0b0ffb7d8f1'
down_revision = 'b8c7ebc6d275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allegro_tokens', sa.Column('belongs_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allegro_tokens', 'belongs_to')
    # ### end Alembic commands ###
